name: CI/CD

on:
  push:
    branches:
      - 'main'

jobs:
  CI_CD:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build the project using Maven
        run: mvn -f ./admin/pom.xml clean install -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER}}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./admin
          push: true
          file: ./admin/Dockerfile
          tags: ruanwill/barber-admin:${{ github.sha }}
