name: CI/CD Pipeline

on:
  push:
    branches:
      - "main"

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build the project using Maven
        run: mvn -f ./admin/pom.xml clean install -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap

      - name: Build Docker image for multiple architectures
        uses: docker/build-push-action@v5
        with:
          context: ./admin
          push: true
          file: ./admin/Dockerfile
          tags: ruanwill/barber-admin:${{ github.sha }}
          platforms: linux/amd64,linux/arm64

  cd:
    name: Continuous Deployment
    runs-on: ubuntu-latest
    needs: ci # O CD só será executado após o CI

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Install OCI CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install oci-cli

      - name: Configure OCI CLI
        run: |
          mkdir -p ~/.oci
          echo "[DEFAULT]" > ~/.oci/config
          echo "user=${{ secrets.OCI_USER_OCID }}" >> ~/.oci/config
          echo "fingerprint=${{ secrets.OCI_FINGERPRINT }}" >> ~/.oci/config
          echo "tenancy=${{ secrets.OCI_TENANCY_OCID }}" >> ~/.oci/config
          echo "region=${{ secrets.OCI_REGION }}" >> ~/.oci/config

          echo "${{ secrets.OCI_PRIVATE_KEY_FILE }}" > ~/.oci/private_key.pem
          echo "key_file=~/.oci/private_key.pem" >> ~/.oci/config

      - name: Create Kubeconfig for OKE
        run: |
          oci ce cluster create-kubeconfig \
            --cluster-id ${{ secrets.OKE_CLUSTER_OCID }} \
            --file $HOME/.kube/config \
            --region ${{ secrets.OCI_REGION }} \
            --overwrite

      - name: Update Deployment with new image
        env:
          KUBECONFIG: $HOME/.kube/config
        run: |
          kubectl set image deployment/barber-admin-deployment \
            barber-admin-container=ruanwill/barber-admin:${{ github.sha }} \
            -n production
